/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagmentsystem;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Toshiba
 */
public class BillDetails extends javax.swing.JFrame {

    /**
     * Creates new form BillDetails
     */
    Connection conn = null;
    Statement smt = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    static String id;

    public BillDetails() {
        initComponents();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        txtsearchbydate.setText(df.format(date));
        ShowDataInCustomerTable();
    }

    public void ShowDataInCustomerTable() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels", "root", "password");
            pst = conn.prepareStatement("Select * from customer where status=?");
            pst.setString(1, "check out");
            rs = pst.executeQuery();
            ResultSetMetaData stData = (ResultSetMetaData) rs.getMetaData();
            int q = stData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel) Table.getModel();
            RecordTable.setRowCount(0);
            while (rs.next()) {
                Vector vector = new Vector();
                for (int i = 1; i <= q; i++) {
                    vector.add(rs.getString("bilid"));
                    vector.add(rs.getString("roomnumber"));
                    vector.add(rs.getString("name"));
                    vector.add(rs.getString("mobile"));
                    vector.add(rs.getString("email"));
                    vector.add(rs.getString("gender"));
                    vector.add(rs.getString("nationality"));
                    vector.add(rs.getString("address"));
                    vector.add(rs.getString("indate"));
                    vector.add(rs.getString("outdate"));
                    vector.add(rs.getString("price"));
                    vector.add(rs.getString("day"));
                    vector.add(rs.getString("amount"));

                }
                RecordTable.addRow(vector);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerCheckout.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchbotton = new javax.swing.JButton();
        refreshbotton = new javax.swing.JButton();
        txtsearchbydate = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Room Number", "Customer Name", "Mobile Number", "Email", "Gender", "Nationality", "Address", "Check in Date", "Check out Date", "Price", "Number of Day", "Total Amount"
            }
        ));
        Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1080, 300));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 108, 100));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill.jpg"))); // NOI18N
        jLabel1.setText("Customer Bill Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 290, 49));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Saerch by Check out Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 179, 27));

        searchbotton.setBackground(new java.awt.Color(204, 0, 0));
        searchbotton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        searchbotton.setForeground(new java.awt.Color(255, 255, 255));
        searchbotton.setText("Search");
        searchbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbottonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        refreshbotton.setBackground(new java.awt.Color(204, 0, 0));
        refreshbotton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        refreshbotton.setForeground(new java.awt.Color(255, 255, 255));
        refreshbotton.setText("Refresh");
        refreshbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbottonActionPerformed(evt);
            }
        });
        getContentPane().add(refreshbotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        txtsearchbydate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchbydateActionPerformed(evt);
            }
        });
        getContentPane().add(txtsearchbydate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 155, 29));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 44, 34));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Double Click on the row to open bill form");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 430, 29));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchbydateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchbydateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchbydateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void refreshbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbottonActionPerformed
        ShowDataInCustomerTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshbottonActionPerformed

    private void searchbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbottonActionPerformed

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels", "root", "password");
            pst = conn.prepareStatement("Select * from customer where status=? AND outdate=?");
            pst.setString(1, "check out");
            pst.setString(2, txtsearchbydate.getText());
            rs = pst.executeQuery();
            ResultSetMetaData stData = (ResultSetMetaData) rs.getMetaData();
            int q = stData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel) Table.getModel();
            RecordTable.setRowCount(0);
            while (rs.next()) {
                Vector vector = new Vector();
                for (int i = 1; i <= q; i++) {
                    vector.add(rs.getString("bilid"));
                    vector.add(rs.getString("roomnumber"));
                    vector.add(rs.getString("name"));
                    vector.add(rs.getString("mobile"));
                    vector.add(rs.getString("email"));
                    vector.add(rs.getString("gender"));
                    vector.add(rs.getString("nationality"));
                    vector.add(rs.getString("address"));
                    vector.add(rs.getString("indate"));
                    vector.add(rs.getString("outdate"));
                    vector.add(rs.getString("price"));
                    vector.add(rs.getString("day"));
                    vector.add(rs.getString("amount"));

                }
                RecordTable.addRow(vector);
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Record Not Found.");
        }

    }//GEN-LAST:event_searchbottonActionPerformed


    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked

        if (evt.getClickCount() == 2) {

            DefaultTableModel ob = (DefaultTableModel) Table.getModel();
            id = (String) ob.getValueAt(Table.getSelectedRow(), 0);
            setVisible(false);
            new BillPrint().setVisible(true);
        }

    }//GEN-LAST:event_TableMouseClicked

    private void TableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMousePressed
        if (evt.getClickCount() == 2) {
            DefaultTableModel ob = (DefaultTableModel) Table.getModel();
            id = (String) ob.getValueAt(Table.getSelectedRow(), 0);
            setVisible(false);
            new BillPrint().setVisible(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_TableMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshbotton;
    private javax.swing.JButton searchbotton;
    private javax.swing.JTextField txtsearchbydate;
    // End of variables declaration//GEN-END:variables
}
