/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagmentsystem;

import java.awt.print.PrinterException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Toshiba
 */
public class BillPrint extends javax.swing.JFrame {

    String id = BillDetails.id;
    String CustomerName;
    String mobile;
    String email;
    String roomnumber;
    String bedtype;
    String roomtype;
    String address;
    String indate;
    String outdate;
    String price;
    String day;
    String total;

    /**
     * Creates new form BillPrint
     */
    public BillPrint() {
        initComponents();
        connect();
        txtbill.setText("\t\t-: Hotel Managment System :-\n");
        txtbill.setText(txtbill.getText() + "**********************************************************************************\n");
        txtbill.setText(txtbill.getText() + "Bill ID:- " + id + "\n");
        txtbill.setText(txtbill.getText() + "Customer Details:- \n");
        txtbill.setText(txtbill.getText() + "Name:- " + CustomerName + "\n");
        txtbill.setText(txtbill.getText() + "Mobile Number:- " + mobile + "\n");
        txtbill.setText(txtbill.getText() + "Email:- " + email + "\n");
        txtbill.setText(txtbill.getText() + "Address:- " + address + "\n");
        txtbill.setText(txtbill.getText() + "**********************************************************************************\n");
        txtbill.setText(txtbill.getText() + "Room Details:- \n");
        txtbill.setText(txtbill.getText() + "Room Number:- " + roomnumber + "\n");
        txtbill.setText(txtbill.getText() + "roomType:- " + roomtype + "\n");
        txtbill.setText(txtbill.getText() + "Bedtype:- " + bedtype + "\n");
        txtbill.setText(txtbill.getText() + "Price:- " + price + "\n");
        txtbill.setText(txtbill.getText() + "Check IN Date=" + indate + "\t\tNumber of Days=" + day + "\n");
        txtbill.setText(txtbill.getText() + "Check OUT Date=" + outdate + "\t\tTotal Amount=" + total + "\n");
        txtbill.setText(txtbill.getText() + "**********************************************************************************\n");
        txtbill.setText(txtbill.getText() + "\t\t" + "                    Thank You,Please Visit Again.");

    }

    public void connect() {
        try {
            PreparedStatement pst = null;
            ResultSet rs = null;

            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels", "root", "password");
            pst = con.prepareStatement("select * from customer where bilid=?");
            pst.setString(1, id);
            rs = pst.executeQuery();
            if (rs.next()) {
                email = rs.getString("email");
                CustomerName = rs.getString("name");
                mobile = rs.getString("mobile");
                roomnumber = rs.getString("roomnumber");
                bedtype = rs.getString("bedtype");
                roomtype = rs.getString("roomtype");
                address=rs.getString("address");
                indate = rs.getString("indate");
                outdate = rs.getString("outdate");
                price = rs.getString("price");
                day = rs.getString("day");
                total = rs.getString("amount");

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BillPrint.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        exitboton = new javax.swing.JButton();
        printboton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbill.setEditable(false);
        txtbill.setColumns(20);
        txtbill.setRows(5);
        jScrollPane1.setViewportView(txtbill);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 530, 337));

        exitboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        exitboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbotonActionPerformed(evt);
            }
        });
        getContentPane().add(exitboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 0, 41, -1));

        printboton.setBackground(new java.awt.Color(255, 153, 51));
        printboton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        printboton.setForeground(new java.awt.Color(45, 7, 17));
        printboton.setText("Print");
        printboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbotonActionPerformed(evt);
            }
        });
        getContentPane().add(printboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" Press Print to Print The Bill");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 290, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbotonActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_exitbotonActionPerformed

    private void printbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbotonActionPerformed
        try {
            txtbill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(BillPrint.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_printbotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitboton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printboton;
    private javax.swing.JTextArea txtbill;
    // End of variables declaration//GEN-END:variables
}
