/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagmentsystem;

import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Toshiba
 */
public class CustomerCheckout extends javax.swing.JFrame {

    Connection conn = null;
    Statement smt = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form CustomerCheckout
     */
    SimpleDateFormat obj = new SimpleDateFormat("yyyy-MM-dd");

    public CustomerCheckout() {
        initComponents();
        Date date = new Date();
        txtcheckout.setText(obj.format(date));

        ShowDataInCustomerTable();
    }


    
    
    public void ShowDataInCustomerTable() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels", "root", "password");
            pst = conn.prepareStatement("Select *from customer where status=?");
            pst.setString(1, "NULL");
            rs = pst.executeQuery();
            
            ResultSetMetaData stData = (ResultSetMetaData) rs.getMetaData();
            int q = stData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel) Table.getModel();
            RecordTable.setRowCount(0);

            while (rs.next()) {
                Vector vector = new Vector();
                for (int i = 1; i <= q; i++) {
                    vector.add(rs.getString("bilid"));
                    vector.add(rs.getString("name"));
                    vector.add(rs.getString("email"));
                    vector.add(rs.getString("mobile"));
                    vector.add(rs.getString("nationality"));
                    vector.add(rs.getString("address"));
                    vector.add(rs.getString("roomnumber"));
                    vector.add(rs.getString("bedtype"));
                    vector.add(rs.getString("roomtype"));
                    vector.add(rs.getString("indate"));
                    vector.add(rs.getString("price"));
                }
                RecordTable.addRow(vector);
            }

        } catch (ClassNotFoundException | SQLException e) { 
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitbotton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtroomnumber = new javax.swing.JTextField();
        searchbotton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcname = new javax.swing.JTextField();
        txtpriceperday = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        txtcheckin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtbillid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtnday = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        checkoutbotton = new javax.swing.JButton();
        clearbotton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtcheckout = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitbotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        exitbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbottonActionPerformed(evt);
            }
        });
        getContentPane().add(exitbotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 48, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 108, 100));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/out.jpg"))); // NOI18N
        jLabel1.setText("Customer Check out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 264, 60));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 93, 33));

        txtroomnumber.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        getContentPane().add(txtroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 164, 30));

        searchbotton.setBackground(new java.awt.Color(204, 0, 0));
        searchbotton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        searchbotton.setForeground(new java.awt.Color(255, 255, 255));
        searchbotton.setText("Search");
        searchbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbottonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 94, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 117, 28));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Price Per Day");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 102, 29));

        txtcname.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        getContentPane().add(txtcname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 187, 31));

        txtpriceperday.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        getContentPane().add(txtpriceperday, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 187, 31));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Mobile Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 111, 30));

        txtmobile.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 179, 30));

        txtcheckin.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        getContentPane().add(txtcheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 187, 33));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Bill ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 114, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Check Out Date(Today)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, 33));

        txtbillid.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        getContentPane().add(txtbillid, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 186, 30));

        Table.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Customer Name", "Email", "Mobile Number", "Nationality", "Address", "Room Number", "Bed Type", "Room Type", "Check in Date", "Price Per Day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 1080, 300));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Number Of Days");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 114, 30));

        txtnday.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        getContentPane().add(txtnday, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 179, 30));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Total Amount");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 118, 28));

        txttotal.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 186, 30));

        checkoutbotton.setBackground(new java.awt.Color(204, 0, 0));
        checkoutbotton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        checkoutbotton.setForeground(new java.awt.Color(255, 255, 255));
        checkoutbotton.setText("Check Out Now");
        checkoutbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutbottonActionPerformed(evt);
            }
        });
        getContentPane().add(checkoutbotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, -1, 39));

        clearbotton.setBackground(new java.awt.Color(204, 0, 0));
        clearbotton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        clearbotton.setForeground(new java.awt.Color(255, 255, 255));
        clearbotton.setText("Clear");
        clearbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbottonActionPerformed(evt);
            }
        });
        getContentPane().add(clearbotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, -1, 39));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Check in Date");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 111, 35));

        txtcheckout.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        getContentPane().add(txtcheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 179, 30));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Click the row automaticaly fill out the box.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 340, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkout22.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 270, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin Home.png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(1094, 791));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        setSize(new java.awt.Dimension(1100, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutbottonActionPerformed
        if (txtcname.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Room Number And Search it,Then Check Out Customer");
        } else {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels", "root", "password");
                pst = con.prepareStatement("update customer set status=? where roomnumber=?");
                pst.setString(1, "check out");
                pst.setString(2, txtroomnumber.getText());
                pst.executeUpdate();
                
                pst = con.prepareStatement("update customer set amount=?,outdate=?,day=? where roomnumber=? AND indate=?");
                pst.setString(1, txttotal.getText());
                pst.setString(2, txtcheckout.getText());
                pst.setString(3, txtnday.getText());
                pst.setString(4, txtroomnumber.getText());
                pst.setString(5, txtcheckin.getText());
                pst.executeUpdate();
                
                pst = con.prepareStatement("update room set status=? where roomnumber=?");
                pst.setString(1, "Not Booked");
                pst.setString(2, txtroomnumber.getText());
                pst.executeUpdate();
                //JOptionPane.showMessageDialog(this,"Check Out Successfully\n Goto to Cutomer Bill Details menu and Print Bill");
                int yes = JOptionPane.showConfirmDialog(this, "Check out Successfully.\nDo you want to see & print bill?", "Check outed", JOptionPane.YES_NO_OPTION);
                if (JOptionPane.YES_OPTION == yes) {
                    setVisible(false);
                    new BillDetails().setVisible(true);
                } else {
                    
                    ShowDataInCustomerTable();
                    
                    txtcname.setText("");
                    txtpriceperday.setText("");
                    txtbillid.setText("");
                    txtmobile.setText("");
                    txtcheckin.setText("");
                    txtnday.setText("");
                    txttotal.setText("");
                    txtroomnumber.setText("");
                }
            } catch (ClassNotFoundException | SQLException e) {
            }
        }


    }//GEN-LAST:event_checkoutbottonActionPerformed


    private void exitbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbottonActionPerformed
        dispose();
    }//GEN-LAST:event_exitbottonActionPerformed


    private void clearbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbottonActionPerformed
        txtcname.setText("");
        txtpriceperday.setText("");
        txtbillid.setText("");
        txtmobile.setText("");
        txtcheckin.setText("");
        txtnday.setText("");
        txttotal.setText("");
    }//GEN-LAST:event_clearbottonActionPerformed


    private void searchbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbottonActionPerformed
        if(txtroomnumber.getText().equals("")){
            JOptionPane.showMessageDialog(this, "The room number required to search.");
        }else{

        txtcname.setText("");
        txtbillid.setText("");
        txtmobile.setText("");
        txtpriceperday.setText("");
        txtcheckin.setText("");

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels", "root", "password");
            pst = conn.prepareStatement("select * from customer where roomnumber=? AND status=?");
            pst.setString(1, txtroomnumber.getText());
            pst.setString(2, "NULL");
            rs = pst.executeQuery();
            if (rs.next()) {
                txtcname.setText(rs.getString("name"));
                txtpriceperday.setText(rs.getString("price"));
                txtcheckin.setText(rs.getString("indate"));
                txtmobile.setText(rs.getString("mobile"));
                txtbillid.setText(rs.getString("bilid"));
            }

            String f1 = txtcheckout.getText();
            String f2 = rs.getString("indate");

            try {
                Date d1 = obj.parse(f1);
                Date d2 = obj.parse(f2);
                long diff = d2.getTime() - d1.getTime();
                int days = (int) (diff / (1000 * 24 * 60 * 60));
                
                if (days == 0) {
                    txtnday.setText("1");
                } else {
                    txtnday.setText(String.valueOf(days));
                }
                
                double p = Double.parseDouble(rs.getString("price"));
                double price = days * p;
                
                if (days == 0) {
                    txttotal.setText(String.valueOf(p));
                } else {
                    txttotal.setText(String.valueOf(price));
                }
            } catch (NumberFormatException | SQLException | ParseException e) {
            }
        } catch (ClassNotFoundException | SQLException ex) {
            txtnday.setText("");
            txttotal.setText("");
            JOptionPane.showMessageDialog(this, "Record Not Found.");
            
        }
     }

    }//GEN-LAST:event_searchbottonActionPerformed

    
    
    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked

        DefaultTableModel RecordTable = (DefaultTableModel) Table.getModel();
        int SelectedRows = Table.getSelectedRow();
        txtroomnumber.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
        txtcname.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        txtmobile.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        txtbillid.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        txtcheckin.setText(RecordTable.getValueAt(SelectedRows, 9).toString());
        txtpriceperday.setText(RecordTable.getValueAt(SelectedRows, 10).toString());

        ZoneId z = ZoneId.of("Asia/Colombo");
        LocalDate todays = LocalDate.now(z);
        String s1 = todays.toString();
        String f1 = RecordTable.getValueAt(SelectedRows, 9).toString();
        String f2 = s1;
        try {
            Date d1 = obj.parse(f1);
            Date d2 = obj.parse(f2);
            long diff = d2.getTime() - d1.getTime();
            int days = (int) (diff / (1000 * 24 * 60 * 60));
            
            if (days == 0) {
                txtnday.setText("1");
            } else {
                txtnday.setText(String.valueOf(days));
            }
            
            double p = Double.parseDouble(RecordTable.getValueAt(SelectedRows, 10).toString());
            double price = days * p;
            
            if (days == 0) {
                txttotal.setText(String.valueOf(p));
            } else {
                txttotal.setText(String.valueOf(price));
            }
        } catch (NumberFormatException | ParseException e) {
        }

    }//GEN-LAST:event_TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton checkoutbotton;
    private javax.swing.JButton clearbotton;
    private javax.swing.JButton exitbotton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchbotton;
    private javax.swing.JTextField txtbillid;
    private javax.swing.JTextField txtcheckin;
    private javax.swing.JTextField txtcheckout;
    private javax.swing.JTextField txtcname;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtnday;
    private javax.swing.JTextField txtpriceperday;
    private javax.swing.JTextField txtroomnumber;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
